sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dpgraham/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true dpgraham/react-app npm test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dpgraham-docker-react"
  env: "DpgrahamDockerReact-env"
  bucket_name: elasticbeanstalk-us-east-2-896766490789
  bucket_path: "dpgraham-docker-react"
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on:
    branch: master